[tool.black]
line-length = 100
target-version = ["py312"]
extend-exclude = "old|logs|images"

[tool.isort]
profile = "black"
line_length = 100
skip_glob = ["old/**", "logs/**", "images/**"]

[tool.ruff]
line-length = 100
extend-exclude = ["old", "logs", "images"]

